const propertyData = [
    {
        id: 1,
        price: 2500,
        place: "New York",
        placeAddress: "123 Broadway, New York",
        propertyType: "Apartment",
        date: "2023-08-10",
        houseName: "Cozy Haven",
    },
    {
        id: 2,
        price: 1200,
        place: "Delhi",
        placeAddress: "456 Main Street, Delhi",
        propertyType: "House",
        date: "2023-08-15",
        houseName: "Tranquil Retreat",
    },
    {
        id: 3,
        price: 35000,
        place: "London",
        placeAddress: "789 Oxford Street, London",
        propertyType: "Condo",
        date: "2023-08-20",
        houseName: "Elegant Residence",
    },
    {
        id: 4,
        price: 800,
        place: "Paris",
        placeAddress: "345 Champs-Élysées, Paris",
        propertyType: "Apartment",
        date: "2023-08-10",
        houseName: "Charming Abode",
    },
    {
        id: 5,
        price: 1800,
        place: "Tokyo",
        placeAddress: "678 Sakura Lane, Tokyo",
        propertyType: "House",
        date: "2023-08-15",
        houseName: "Serene House",
    },
    {
        id: 6,
        price: 6000,
        place: "Sydney",
        placeAddress: "567 Harbor Road, Sydney",
        propertyType: "Townhouse",
        date: "2023-08-20",
        houseName: "Harbor View Residence",
    },
    {
        id: 7,
        price: 2000,
        place: "New York",
        placeAddress: "612 Bleacker Street , Ney York",
        propertyType: "Studio",
        date: "2023-09-01",
        houseName: "Regal Manor",
    },
    {
        id: 8,
        price: 3500,
        placeAddress: "678 Park Avenue, Delhi",
        place: "Delhi",
        propertyType: "Apartment",
        date: "2023-09-10",
        houseName: "Zen Residence",
    },
    {
        id: 9,
        price: 22000,
        place: "London",
        placeAddress: "Stark Corporation , London",
        propertyType: "House",
        date: "2023-09-20",
        houseName: "Oceanfront Retreat",
    },
    {
        id: 10,
        price: 700,
        place: "Paris",
        placeAddress: "123 Rue de Rivoli, Paris",
        propertyType: "Condo",
        date: "2023-09-01",
        houseName: "Modern Oasis",
    },
    {
        id: 11,
        price: 1500,
        place: "Tokyo",
        placeAddress: "456 Yorknew Park , Tokyo",
        propertyType: "Apartment",
        date: "2023-09-10",
        houseName: "Stamford Bridge",
    },
    {
        id: 12,
        price: 4500,
        place: "Sydney",
        placeAddress: "789 Greed island, Sydney",
        propertyType: "House",
        date: "2023-09-20",
        houseName: "Anfield"
    },
    {
        id: 13,
        price: 3000,
        place: "New York",
        placeAddress: "890 Central Avenue, New York",
        propertyType: "Condo",
        date: "2023-09-01",
        houseName: "Old Trafford",
    },
    {
        id: 14,
        price: 1000,
        place: "Delhi",
        placeAddress: "234 Garden Street, Delhi",
        propertyType: "Apartment",
        date: "2023-09-10",
        houseName: "San Siro",
    },
];

export default propertyData;
